### Train a simple deep neural network on the MNIST dataset

#### Gets to 98.18% test accuracy after 20 epochs (there is a lot of margin for parameter tuning).

In [1]:
from __future__ import print_function

import tensorflow.keras as keras
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.optimizers import RMSprop

In [5]:
batch_size = 128
num_classes = 10
epochs = 20

# the data, shuffled and split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train = x_train.reshape(60000, 784)
x_test = x_test.reshape(10000, 784)
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
print(x_train.shape, 'train samples')
print(x_test.shape, 'test samples')

(60000, 784) train samples
(10000, 784) test samples


In [6]:
# convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

In [7]:
print(y_train.shape, y_test.shape)
print(y_train)

(60000, 10) (10000, 10)
[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [8]:
model = Sequential()
model.add(Dense(512, activation='relu', input_shape=(784,)))
model.add(Dropout(0.2))
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(num_classes, activation='softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer=RMSprop(),
              metrics=['accuracy'])

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 512)               401920    
_________________________________________________________________
dropout (Dropout)            (None, 512)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 512)               262656    
_________________________________________________________________
dropout_1 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 10)                5130      
Total params: 669,706
Trainable params: 669,706
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# #some learners constantly reported 502 errors in Watson Studio. 
# #This is due to the limited resources in the free tier and the heavy resource consumption of Keras.
# #This is a workaround to limit resource consumption

# from keras import backend as K

# K.set_session(K.tf.Session(config=K.tf.ConfigProto(intra_op_parallelism_threads=1, inter_op_parallelism_threads=1)))

In [10]:
history = model.fit(x_train, y_train,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=1,
                    validation_data=(x_test, y_test))
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Epoch 1/20
469/469 [==============================] - 4s 8ms/step - loss: 0.2474 - accuracy: 0.9239 - val_loss: 0.1174 - val_accuracy: 0.9629
Epoch 2/20
469/469 [==============================] - 4s 9ms/step - loss: 0.1020 - accuracy: 0.9690 - val_loss: 0.0829 - val_accuracy: 0.9758
Epoch 3/20
469/469 [==============================] - 4s 8ms/step - loss: 0.0747 - accuracy: 0.9771 - val_loss: 0.0753 - val_accuracy: 0.9783
Epoch 4/20
469/469 [==============================] - 4s 9ms/step - loss: 0.0607 - accuracy: 0.9818 - val_loss: 0.0832 - val_accuracy: 0.9768
Epoch 5/20
469/469 [==============================] - 4s 8ms/step - loss: 0.0502 - accuracy: 0.9847 - val_loss: 0.0751 - val_accuracy: 0.9815
Epoch 6/20
469/469 [==============================] - 4s 9ms/step - loss: 0.0441 - accuracy: 0.9869 - val_loss: 0.0738 - val_accuracy: 0.9812
Epoch 7/20
469/469 [==============================] - 4s 9ms/step - loss: 0.0386 - accuracy: 0.9886 - val_loss: 0.0872 - val_accuracy: 0.9805
Epoch 